# knife4j聚合配置
knife4j:
  enableAggregation: true
  # cloud模式
  cloud:
    # 是否启用
    enable: true
    # 网关地址
    gatewayUri: 127.0.0.1:8080
    # 需要聚合的服务集合
    routes:
      - name: 系统服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /system/v2/api-docs
      - name: 开放平台
        uri: ${knife4j.cloud.gatewayUri}
        location: /platform/v2/api-docs
      - name: sdk
        uri: ${knife4j.cloud.gatewayUri}
        location: /sdk/v2/api-docs
      - name: 资源服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /resource/v2/api-docs
      - name: 认证服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /auth/v2/api-docs
      - name: 支付订单服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /payment/v2/api-docs
      - name: 数据统计服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /statistics/v2/api-docs
      - name: 社区动态服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /community/v2/api-docs
      - name: 封控服务
        uri: ${knife4j.cloud.gatewayUri}
        location: /risk/v2/api-docs

