# 监控中心配置
spring:
  security:
    user:
      name: euler
      password: abcdefg
  boot:
    admin:
      ui:
        title: Euler-Cloud服务监控中心
      discovery:
        # seata 不具有健康检查的能力 防止报错排除掉
        ignored-services: seata-server
